const clientsMockData = [
  {
    id: 1,
    name: "Client 1",
    email: "client1@example.com",
    phone: "123-456-7890",
    address: "123 Main St",
    company: "ABC Inc",
    contactPerson: "John Doe",
    notes: "VIP client",
  },
  {
    id: 2,
    name: "Client 2",
    email: "client2@example.com",
    phone: "456-789-0123",
    address: "456 Elm St",
    company: "XYZ Corp",
    contactPerson: "Jane Smith",
    notes: "Preferred vendor",
  },
  {
    id: 3,
    name: "Client 3",
    email: "client3@example.com",
    phone: "789-012-3456",
    address: "789 Oak St",
    company: "123 Enterprises",
    contactPerson: "Bob Johnson",
    notes: "Regular customer",
  },
  {
    id: 4,
    name: "Client 4",
    email: "client4@example.com",
    phone: "012-345-6789",
    address: "012 Pine St",
    company: "Acme Co",
    contactPerson: "Alice Adams",
    notes: "New prospect",
  },
  {
    id: 5,
    name: "Client 5",
    email: "client5@example.com",
    phone: "345-678-9012",
    address: "345 Cedar St",
    company: "Smith & Sons",
    contactPerson: "Jim Brown",
    notes: "Long-term partner",
  },
  {
    id: 6,
    name: "Client 6",
    email: "client6@example.com",
    phone: "678-901-2345",
    address: "678 Maple St",
    company: "Johnson Industries",
    contactPerson: "Sarah Wilson",
    notes: "Special discount",
  },
  {
    id: 7,
    name: "Client 7",
    email: "client7@example.com",
    phone: "901-234-5678",
    address: "901 Walnut St",
    company: "Big Corp",
    contactPerson: "Mike Davis",
    notes: "International client",
  },
  {
    id: 8,
    name: "Client 8",
    email: "client8@example.com",
    phone: "234-567-8901",
    address: "234 Birch St",
    company: "Tech Solutions",
    contactPerson: "Emily Miller",
    notes: "Referral from friend",
  },
  {
    id: 9,
    name: "Client 9",
    email: "client9@example.com",
    phone: "567-890-1234",
    address: "567 Oak St",
    company: "Global LLC",
    contactPerson: "Tom Wilson",
    notes: "Discount for bulk orders",
  },
  {
    id: 10,
    name: "Client 10",
    email: "client10@example.com",
    phone: "890-123-4567",
    address: "890 Pine St",
    company: "Creative Design",
    contactPerson: "Mary Johnson",
    notes: "Frequent buyer",
  },
  {
    id: 11,
    name: "Client 11",
    email: "client11@example.com",
    phone: "123-456-7890",
    address: "123 Cedar St",
    company: "Innovative Solutions",
    contactPerson: "Alex Brown",
    notes: "Custom orders",
  },
  {
    id: 12,
    name: "Client 12",
    email: "client12@example.com",
    phone: "456-789-0123",
    address: "456 Elm St",
    company: "Smith Enterprises",
    contactPerson: "Karen Taylor",
    notes: "Exclusive contract",
  },
];
export default clientsMockData;
