const ordersMockData = [
  {
    id: 1,
    customerName: "Client 1",
    orderDate: "2024-03-14",
    status: "Pending",
    expectedDeliveryDate: "2024-03-15",
    items: [
      { name: "Laptop", price: 999, quantity: 1 },
      { name: "Smartphone", price: 699, quantity: 2 },
    ],
    totalAmount: 2397,
    shippingAddress: "123 Main St",
    paymentStatus: "Paid",
    transactionId: "TXN123456",
  },
  {
    id: 2,
    customerName: "Client 2",
    orderDate: "2024-02-02",
    status: "Shipped",
    expectedDeliveryDate: "2024-02-06",
    items: [
      { name: "Headphones", price: 99, quantity: 1 },
      { name: "Running Shoes", price: 79, quantity: 1 },
    ],
    totalAmount: 178,
    shippingAddress: "456 Elm St",
    paymentStatus: "Pending",
    transactionId: "",
  },
  {
    id: 3,
    customerName: "Client 3",
    orderDate: "2024-03-05",
    status: "Delivered",
    expectedDeliveryDate: "2024-03-09",
    items: [{ name: "Yoga Mat", price: 29, quantity: 3 }],
    totalAmount: 87,
    shippingAddress: "789 Oak St",
    paymentStatus: "Paid",
    transactionId: "TXN789012",
  },
  {
    id: 4,
    customerName: "Client 4",
    orderDate: "2024-04-08",
    status: "Pending",
    expectedDeliveryDate: "2024-04-12",
    items: [{ name: "Dumbbells", price: 49, quantity: 2 }],
    totalAmount: 98,
    shippingAddress: "012 Pine St",
    paymentStatus: "Pending",
    transactionId: "",
  },
  {
    id: 5,
    customerName: "Client 5",
    orderDate: "2024-05-10",
    status: "Shipped",
    expectedDeliveryDate: "2024-05-14",
    items: [{ name: "Sunglasses", price: 39, quantity: 1 }],
    totalAmount: 39,
    shippingAddress: "345 Cedar St",
    paymentStatus: "Paid",
    transactionId: "TXN345678",
  },
  {
    id: 6,
    customerName: "Client 6",
    orderDate: "2024-06-11",
    status: "Delivered",
    expectedDeliveryDate: "2024-06-15",
    items: [{ name: "Coffee Maker", price: 129, quantity: 1 }],
    totalAmount: 129,
    shippingAddress: "678 Maple St",
    paymentStatus: "Paid",
    transactionId: "TXN678901",
  },
  {
    id: 7,
    customerName: "Client 7",
    orderDate: "2024-07-14",
    status: "Pending",
    expectedDeliveryDate: "2024-07-18",
    items: [{ name: "Toaster", price: 49, quantity: 1 }],
    totalAmount: 49,
    shippingAddress: "901 Walnut St",
    paymentStatus: "Pending",
    transactionId: "",
  },
  {
    id: 8,
    customerName: "Client 8",
    orderDate: "2024-08-16",
    status: "Shipped",
    expectedDeliveryDate: "2024-08-20",
    items: [{ name: "Vacuum Cleaner", price: 199, quantity: 1 }],
    totalAmount: 199,
    shippingAddress: "234 Birch St",
    paymentStatus: "Paid",
    transactionId: "TXN234567",
  },
  {
    id: 9,
    customerName: "Client 9",
    orderDate: "2024-09-20",
    status: "Delivered",
    expectedDeliveryDate: "2024-09-24",
    items: [{ name: "Jeans", price: 59, quantity: 2 }],
    totalAmount: 118,
    shippingAddress: "567 Oak St",
    paymentStatus: "Paid",
    transactionId: "TXN567890",
  },
  {
    id: 10,
    customerName: "Client 10",
    orderDate: "2024-10-21",
    status: "Pending",
    expectedDeliveryDate: "2024-10-25",
    items: [{ name: "T-Shirt", price: 19, quantity: 3 }],
    totalAmount: 57,
    shippingAddress: "890 Pine St",
    paymentStatus: "Pending",
    transactionId: "",
  },
  {
    id: 11,
    customerName: "Client 11",
    orderDate: "2024-11-24",
    status: "Shipped",
    expectedDeliveryDate: "2024-11-28",
    items: [{ name: "Laptop", price: 999, quantity: 1 }],
    totalAmount: 999,
    shippingAddress: "123 Cedar St",
    paymentStatus: "Paid",
    transactionId: "TXN123123",
  },
  {
    id: 12,
    customerName: "Client 12",
    orderDate: "2024-12-25",
    status: "Delivered",
    expectedDeliveryDate: "2024-12-29",
    items: [{ name: "Smartphone", price: 699, quantity: 1 }],
    totalAmount: 699,
    shippingAddress: "456 Elm St",
    paymentStatus: "Paid",
    transactionId: "TXN456456",
  },
  {
    id: 13,
    customerName: "Client 1",
    orderDate: "2024-02-15",
    status: "Delivered",
    expectedDeliveryDate: "2024-02-19",
    items: [
      { name: "Headphones", price: 99, quantity: 1 },
      { name: "Dumbbells", price: 49, quantity: 2 },
    ],
    totalAmount: 197,
    shippingAddress: "123 Main St",
    paymentStatus: "Paid",
    transactionId: "TXN789789",
  },
  {
    id: 14,
    customerName: "Client 2",
    orderDate: "2024-03-20",
    status: "Pending",
    expectedDeliveryDate: "2024-03-24",
    items: [{ name: "Yoga Mat", price: 29, quantity: 3 }],
    totalAmount: 87,
    shippingAddress: "456 Elm St",
    paymentStatus: "Pending",
    transactionId: "",
  },
  {
    id: 15,
    customerName: "Client 3",
    orderDate: "2024-03-15",
    status: "Shipped",
    expectedDeliveryDate: "2024-03-19",
    items: [{ name: "Smartphone", price: 699, quantity: 1 }],
    totalAmount: 699,
    shippingAddress: "789 Oak St",
    paymentStatus: "Paid",
    transactionId: "TXN456789",
  },
  {
    id: 16,
    customerName: "Client 4",
    orderDate: "2024-05-05",
    status: "Delivered",
    expectedDeliveryDate: "2024-05-09",
    items: [{ name: "Coffee Maker", price: 129, quantity: 1 }],
    totalAmount: 129,
    shippingAddress: "012 Pine St",
    paymentStatus: "Paid",
    transactionId: "TXN987654",
  },
  {
    id: 17,
    customerName: "Client 5",
    orderDate: "2024-06-18",
    status: "Pending",
    expectedDeliveryDate: "2024-06-22",
    items: [{ name: "Toaster", price: 49, quantity: 1 }],
    totalAmount: 49,
    shippingAddress: "345 Cedar St",
    paymentStatus: "Pending",
    transactionId: "",
  },
  {
    id: 18,
    customerName: "Client 6",
    orderDate: "2024-03-15",
    status: "Shipped",
    expectedDeliveryDate: "2024-03-27",
    items: [{ name: "Vacuum Cleaner", price: 199, quantity: 1 }],
    totalAmount: 199,
    shippingAddress: "678 Maple St",
    paymentStatus: "Paid",
    transactionId: "TXN654321",
  },
  {
    id: 19,
    customerName: "Client 7",
    orderDate: "2024-03-15",
    status: "Pending",
    expectedDeliveryDate: "2024-03-19",
    items: [
      { name: "Sneakers", price: 89, quantity: 1 },
      { name: "Backpack", price: 59, quantity: 1 },
    ],
    totalAmount: 148,
    shippingAddress: "901 Walnut St",
    paymentStatus: "Pending",
    transactionId: "",
  },
  {
    id: 20,
    customerName: "Client 8",
    orderDate: "2024-09-05",
    status: "Shipped",
    expectedDeliveryDate: "2024-09-09",
    items: [
      { name: "Smartwatch", price: 199, quantity: 1 },
      { name: "Fitness Tracker", price: 79, quantity: 1 },
    ],
    totalAmount: 278,
    shippingAddress: "234 Birch St",
    paymentStatus: "Paid",
    transactionId: "TXN765432",
  },
  {
    id: 21,
    customerName: "Client 9",
    orderDate: "2024-10-15",
    status: "Delivered",
    expectedDeliveryDate: "2024-10-19",
    items: [
      { name: "Wireless Mouse", price: 29, quantity: 2 },
      { name: "Keyboard", price: 49, quantity: 1 },
    ],
    totalAmount: 107,
    shippingAddress: "567 Oak St",
    paymentStatus: "Paid",
    transactionId: "TXN101010",
  },
  {
    id: 22,
    customerName: "Client 10",
    orderDate: "2024-11-20",
    status: "Pending",
    expectedDeliveryDate: "2024-11-24",
    items: [
      { name: "Bluetooth Speaker", price: 99, quantity: 1 },
      { name: "Power Bank", price: 39, quantity: 2 },
    ],
    totalAmount: 177,
    shippingAddress: "890 Pine St",
    paymentStatus: "Pending",
    transactionId: "",
  },
  {
    id: 23,
    customerName: "Client 11",
    orderDate: "2024-12-05",
    status: "Shipped",
    expectedDeliveryDate: "2024-12-09",
    items: [
      { name: "Digital Camera", price: 499, quantity: 1 },
      { name: "Tripod", price: 69, quantity: 1 },
    ],
    totalAmount: 568,
    shippingAddress: "123 Cedar St",
    paymentStatus: "Paid",
    transactionId: "TXN110011",
  },
  {
    id: 24,
    customerName: "Client 12",
    orderDate: "2024-01-25",
    status: "Delivered",
    expectedDeliveryDate: "2024-01-29",
    items: [
      { name: "Wireless Earbuds", price: 129, quantity: 1 },
      { name: "External Hard Drive", price: 149, quantity: 1 },
    ],
    totalAmount: 278,
    shippingAddress: "456 Elm St",
    paymentStatus: "Paid",
    transactionId: "TXN121212",
  },
];
export default ordersMockData;
