const productsMockData = [
  {
    id: 1,
    name: "Laptop",
    category: "Electronics",
    price: 999,
    stockQuantity: 20,
  },
  {
    id: 2,
    name: "Smartphone",
    category: "Electronics",
    price: 699,
    stockQuantity: 30,
  },
  {
    id: 3,
    name: "Headphones",
    category: "Electronics",
    price: 99,
    stockQuantity: 50,
  },
  {
    id: 4,
    name: "Running Shoes",
    category: "Sports",
    price: 79,
    stockQuantity: 40,
  },
  { id: 5, name: "Yoga Mat", category: "Sports", price: 29, stockQuantity: 60 },
  {
    id: 6,
    name: "Dumbbells",
    category: "Sports",
    price: 49,
    stockQuantity: 25,
  },
  {
    id: 7,
    name: "Sunglasses",
    category: "Fashion",
    price: 39,
    stockQuantity: 35,
  },
  { id: 8, name: "T-Shirt", category: "Fashion", price: 19, stockQuantity: 70 },
  { id: 9, name: "Jeans", category: "Fashion", price: 59, stockQuantity: 45 },
  {
    id: 10,
    name: "Coffee Maker",
    category: "Home & Kitchen",
    price: 129,
    stockQuantity: 15,
  },
  {
    id: 11,
    name: "Toaster",
    category: "Home & Kitchen",
    price: 49,
    stockQuantity: 25,
  },
  {
    id: 12,
    name: "Vacuum Cleaner",
    category: "Home & Kitchen",
    price: 199,
    stockQuantity: 10,
  },
];
export default productsMockData;
